In [1]:
x=10
print(x)

10


In [3]:
print("va\\nshthakur")

va\nshthakur


In [4]:
x=2
y=4
print(x)  #value fetched from memory not from script
print(y)  #value fetched from memory not from script

2
4


In [5]:
x=2
y=4
X=5
print(x)
print(y)
print(X)
x=10
y=45
print(x)
print(y)

2
4
5
10
45


In [ ]:
#ascai code:- 0-255= 256

In [ ]:
#ascai code3463467658
#bianry code: @##%$^&$^&^%%$#

In [ ]:
2x=4

In [ ]:
#A=65 B=66........Z=90
#a=97 b=98 .......z=112
#esc=27 enter=13

In [6]:
x= 5
y=4
z=x+y #first right hand side is solved before assigning value to variable
print("Sum of values",z)

Sum of values 9


In [7]:
a=120
b=12.34
c= "new"
print(type(a))
print(type(b))
print(type(c))

<class 'int'>
<class 'float'>
<class 'str'>


In [8]:
"hello" + "world" #concatination 

'helloworld'

In [9]:
#input is used for keyboard input
x= input() #by default input takes the value as string and to change the data type we use the technique of type casting:
y= input()
z= x+y
print("sum of values",z)

13
14
sum of values 1314


In [10]:
a=10
b=4
c=a/b #implicit type casting
print(type(a), type(b), type(c))

<class 'int'> <class 'int'> <class 'float'>


In [13]:
x= int(input("enter the value="))
y=int(input("enter a value= "))
z=x+y
print("sum of values",z)

enter the value=12
enter a value= 14
sum of values 26


In [14]:
# //used for quotient

In [15]:
#syntax of if/else
#if_data if condition else else_data

In [16]:
a=int(input("enter a:"))
b=int(input("enter b:"))
print("hello") if a==b else print("bye")

enter a:12
enter b:13
bye


In [17]:
#for identifying odd and even no.
a=int(input("provide a no:"))
print ("even") if a%2==0 else print("odd")

provide a no:5
odd


In [20]:
print("Welcome\n")
print("Vansh Thakur")
print("from Harayana")
print("Bank name : SBI")
print("acc no.: 12345678")
print("ATM Pin: 1234")
print("acc balance:100000\n")
print("Thanks\n")

Welcome

Vansh Thakur
from Harayana
Bank name : SBI
acc no.: 12345678
ATM Pin: 1234
acc balance:100000

Thanks



In [25]:
print("Welcome\n")
print("Vansh Thakur")
saved_password= 1234
user_password=int(input("Enter password for back deails:"))
if saved_password==user_password:
    print("from Harayana")
    print("Bank name : SBI")
    print("acc no.: 12345678")
    print("ATM Pin: 1234")
    print("acc balance:100000\n")
else:
    print("wrong password please try again\n")
    

Welcome

Vansh Thakur
Enter password for back deails:121212
wrong password please try again



In [1]:
import getpass
print("Welcome\n")
print("Vansh Thakur")
saved_password= 1234
user_password=int(getpass.getpass("Enter password for bank deails:"))
if saved_password==user_password:
    print("from Harayana")
    print("Bank name : SBI")
    print("acc no.: 12345678")
    print("ATM Pin: 1234")
    print("acc balance:100000\n")
else:
    print("wrong password please try again\n")
print("Thanks\n")

Welcome

Vansh Thakur
Enter password for bank deails:········
from Harayana
Bank name : SBI
acc no.: 12345678
ATM Pin: 1234
acc balance:100000

Thanks



In [33]:
#nested if else
import getpass
print("Welcome\n")
print("Vansh Thakur")
saved_password= 1234
user_password=int(getpass.getpass("Enter password for back deails:"))
if saved_password==user_password:
    print("from Harayana")
    print("Bank name : SBI")
    print("acc no.: 12345678")
    pp=5678
    upp=int(getpass.getpass("Enter UPP:"))
    if pp==upp:
        print("ATM Pin: 1234")
        print("acc balance:100000\n")
    else:
        print("Wrong PP")
else:
    print("wrong password please try again\n")
print("Thanks\n")

Welcome

Vansh Thakur
Enter password for back deails:········
from Harayana
Bank name : SBI
acc no.: 12345678
Enter UPP:········
Wrong PP
Thanks



In [ ]:
#elif statements
l=input("enter 1st alphabat of colour name: ")
if l=="r":
    print("red")
elif l=="y":
    print("yellow")
elif l=="g":
    print("green")
else:
    print("wrong input")

In [36]:
#loop   for and while

In [37]:
x=1
x=x+1 #x+=1
print(x)

2


In [40]:
x=10
x=x-1      #x-=1
print(x)

9


In [1]:
print("Welcome\n")
i=1
while i<=3:
    print("hello world")
    i=i+1
print("\nThanks")

Welcome

hello world
hello world
hello world

Thanks


In [2]:
print("Welcome\n")
i=1
n=int(input("enter data"))
while i<=n:
    print("hello world")
    i=i+1
print("\nThanks")

Welcome

enter data5
hello world
hello world
hello world
hello world
hello world

Thanks


In [2]:
print("Welcome\n")
i=1
n=int(input("enter data"))
while i<=n:
    print("hello world")
    i=i+1
print("\nThanks")

Welcome

enter data34
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world

Thanks


In [3]:
x=1
print(x)

1


In [4]:
print("welcome")
while True:
    print("Hello World")
    choice=input ("do you want to run again y/n:")
    if choice=="n":
        break
print("\n Thanks")

welcome
Hello World
do you want to run again y/n:y
Hello World
do you want to run again y/n:n

 Thanks


In [1]:
print("welcome")
i=1
while True:
    print(i,"Hello World")
    if i%3==0:
        choice=input ("do you want to run again y/n:")
        if choice=="n":
            break
    i+=1
print("\n Thanks")

welcome
1 Hello World
2 Hello World
3 Hello World
do you want to run again y/n:y
4 Hello World
5 Hello World
6 Hello World
do you want to run again y/n:n

 Thanks


In [2]:
s=int(input("Enter the starting value= "))
e=int(input("Enter the end      value="))
l=0
for i in range(s,e+1):
    if i%3==0 and i%5==0:
        print(i)
        l+=1
print("Total no. of nos",l)

Enter the starting value= 1
Enter the end      value=100
15
30
45
60
75
90
Total no. of nos 6


In [2]:
s=int(input("Enter the starting value= "))
e=int(input("Enter the end      value="))
l=0
while s<=e:
    if s%3==0 and s%5==0:
        l+=1
    s=s+1
print("Total no. of nos",l)

Enter the starting value= 10
Enter the end      value=1000
Total no. of nos 66


In [12]:
#program to find prime no.s
n=int(input("Enter a no to check"))
flag=1
for i in range(2,n):
    if n%i==0:
        flag=0
if flag==1:
    print("No. is prime")
else:
    print("No is not Prime")

Enter a no to check4
No is not Prime


In [21]:
s=int(input("Enter the Start Value "))
e=int(input("Enter the End   Value "))
l=0

for m in range (s,e+1):
    flag=1
    for i in range(2,m):
        if m%i==0:
            flag=0
    if flag==1:
        print(m,"No. is Prime")
        l+=1
print("Total no,s of prime no.=",l)

Enter the Start Value 2
Enter the End   Value 20
2 No. is Prime
3 No. is Prime
5 No. is Prime
7 No. is Prime
11 No. is Prime
13 No. is Prime
17 No. is Prime
19 No. is Prime
Total no,s of prime no.= 8


In [15]:
s=int(input("Enter the Start Value"))
e=int(input("Enter the End   Value"))
l=0
while s<=e:
    
    i=2
    flag=1
    while i<s:
        if s%i==0:
            flag=0
        i+=1
    if flag==1:
        print("Prime no. is",s)
        l+=1
    s+=1
print("total prime no.s=",l)

Enter the Start Value1
Enter the End   Value5
Prime no. is 1
Prime no. is 2
Prime no. is 3
Prime no. is 5
total prime no.s= 4


In [18]:
n=int(input("enter the no."))
m=0
while n>0:
    n=n//10
    m+=1
print("total digit: ",m)

enter the no.123456
total digit:  6


In [7]:
#to check if the no. is inverse of it self
n=int(input("Enter the no.: "))
m=n           #to store the original value for comparison
rev=0         #to build up the reverse order of the no.
while n>0:
    r=n%10
    rev=rev*10+r
    n=n//10
if rev==m:
    print("Both sides are same")
else:
    print("Both sides are not same")

Enter the no.: 10
Both sides are not same


In [17]:
n=int(input("Enter a no."))
for i in range(1,n+1):
    for j in range(1,n+1):
        print(i,end=" ")
    print()

Enter a no.5
1 1 1 1 1 
2 2 2 2 2 
3 3 3 3 3 
4 4 4 4 4 
5 5 5 5 5 


In [3]:
n=int(input("Enter a no."))
for i in range(1,n+1):
    for j in range(1,n+1):
        print(j,end=" ")
    print()
        

Enter a no.5
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 
1 2 3 4 5 


In [1]:
def sharmaji(b):
    print("I am deepak sharma")
    print ("from UP")
    total_b=b+(b*(10/100))
    return total_b

In [2]:
print("hello world")
my_bal=int(input("Enter Money: "))
tushar=sharmaji(my_bal)
print("My current balance:",tushar)

hello world
Enter Money: 100
I am deepak sharma
from UP
My current balance: 110.0


In [16]:
#tupple is static list is dynamic

In [19]:
import os
os.getcwd()

'C:\\Users\\Vansh\\Documents\\python training'

In [20]:
#syntax for importing other python file 
#import filename
#to call a function from imported file
#filename.function

In [22]:
#to import a file from different folder '
#from foldername import filename
#to assign the variable to imported file
#from foldername import filename as verable

In [7]:
import vansh

In [8]:
vansh.thakur()

My name is Vansh
I am from haryana


# SQLite 3

In [1]:
import sqlite3

In [2]:
#file handling

In [3]:
h=open("Vansh.txt","w")
print (h)

<_io.TextIOWrapper name='Vansh.txt' mode='w' encoding='cp1252'>


In [4]:
print("Welcome")
h=open("vt.txt","w")
h.write("Go to hell")
h.write("\nfuck off")
h.close()
print("thanks")

Welcome
thanks


In [5]:
print("Welcome")
h=open("vt.txt","a")
h.write("\n\nmother fucker")
h.write("\nSon of a bitch")
h.close()
print("thanks")

Welcome
thanks


In [6]:
k=open("vt.txt","r")
p=k.read()
print(p)

Go to hell
fuck off

mother fucker
Son of a bitch


In [7]:
#write function 
k=open("History.txt","w")
title= "HISTORY OF INDIA"
p1="\nhello everyone"
k.write(title)
k.write(p1)
k.close()

In [8]:
#append function
apnd=open("History.txt","a")
last="\nIndia is a vast country which contains people of multiple religion."
apnd.write(last)
apnd.close()

In [9]:
print("Welcome")
h=open("pp.txt","w")
name="i am VPIS"
address="\nRohini"
h.write(name)
h.write(address)
h.close()#save and close
print("Thanks")

Welcome
Thanks


In [10]:
print("Welcome")
h=open("pp.txt","a")
name="\n\ni am JNU"
address="\nJaipuir"
h.write(name)
h.write(address)
h.close()#save and close
print("Thanks")

Welcome
Thanks


In [11]:
k=open("History.txt","r")
print(k)

<_io.TextIOWrapper name='History.txt' mode='r' encoding='cp1252'>


In [12]:
k=open("History.txt","r")
o=k.read()
print(o)

HISTORY OF INDIA
hello everyone
India is a vast country which contains people of multiple religion.


In [13]:
o

'HISTORY OF INDIA\nhello everyone\nIndia is a vast country which contains people of multiple religion.'

# SQLite3 DataBase Management Project

In [14]:
import sqlite3

In [15]:
#bridge
con=sqlite3.connect("Name.db") 

In [16]:
#truck
c=con.cursor()

In [17]:
c.execute("create table cmp (name txt,age int, city txt)")

OperationalError: table cmp already exists

In [18]:
c.execute("insert into cmp values ('Vansh Thakur',19, 'Delhi')")

In [19]:
c.execute("insert into cmp values ('Kinjal',15,'delhi')")

In [20]:
con.commit()  #save

In [21]:
c.execute("select * from cmp") #* means for all

In [22]:
data=c.fetchall()
data

[('Vansh Thakur', 19, 'Delhi'),
 ('Kinjal', 15, 'delhi'),
 ('Vansh Thakur', 19, 'Delhi'),
 ('Kinjal', 15, 'delhi')]

In [23]:
import sqlite3
con=sqlite3.connect("ducat.db")
c=con.cursor()
c.execute("create table Student (ID int unique, Name txt, Marks float, Mobile int, Email str)")


OperationalError: table Student already exists

In [24]:
def insert():
    cnfrminsert=input("Confirm to insert data (y/n)").lower()
    if cnfrminsert=="y":
        i=1
        while True:
            a=int(input("Enter the id="))
            b=input("Enter name= ")
            c1=float(input("Enter Marks"))
            d=int(input("Enter your Mobile no.= "))
            e=input("Enter email id= ")
            c.execute("insert into Student values (?,?,?,?,?)",(a,b,c1,d,e))
            print("Data Inserted")
            choiceinsert= input("Press Y to enter more data else press N").lower()
            if choiceinsert=="n":
                break
                
    elif cnfrminsert=="n":
        print("Thanks for Visiting")
        choice()
    else:
        print("Enter a valid option")
        insert()
    

In [25]:
def read():
    c.execute("select * from Student")
    data= c.fetchall()
    print (data)
    choice()

In [26]:
def delete():
    d1=int(input("Enter the no. of data items to delete= "))
    for i in range (0,d1):
        d2=int(input("Enter ID to delete= "))
        c.execute("delete from student where ID='d2'")
    print("DATA DELETED")
    choice()

In [27]:
def updatefunction():
    print("WELCOME \n")
    def updateid():
        cnfrmid=input("Confirm to change the id(Yes/No): ").lower()
        if cnfrmid=="yes":
            i=1
            while True:
                idu=int(input("Enter Previous ID to update= "))
                idu1=int(input("Enter new ID= "))
                c.execute("update Student set ID='idu1' where ID='idu'")
                print("ID Updated")
                choiceid=input("Do you want to change another id (Y/N):").upper()
                if choiceid=="N":
                    break
            
        elif cnfrm== "no":
            print("Thanks for your visit \n")
            updatefunction()
        else:
            print("Enter a valid answer \n")
            updateid()
    def updatename():
        cnfrmname=input("Do you want to change the name= ").lower()
        if cnfrmname== "yes":
            i=1
            while True:
                un=input("Enter the ID of the name to update= ")
                un1=input("Enter new Name= ")
                c.execute("update Student set Name='un1' where ID= 'un' ")
                print("Name Updated")
                choicename=input("Do you want to change another name (y\n)")
                if choicename=="n":
                    break
        elif cnfrm== "no":
            print("Thanks for your visit \n")
            updatefunction()
        else:
            print("Enter a valid answer \n")
            updatename()
    def updatemarks():
        cnfrmmarks=input("Confirm to update marks (y/n):").lower()
        if cnfrmmarks=="y":
            i=1
            while True:
                um=int(input("Enter the ID of the student of update= "))
                um1=float(input("ENTER UPDATED MARKS= "))
                c.execute("update Student set Marks='um1' where ID='um'")
                print("Marks UPDATED")
                choicemarks=input("DO YOU WANT TO UPDATE ANOTHER MARKS (Y/N)").upper()
                if choicemarks=="N":
                    break
        elif cnfrmmarks=="n":
            print("Thanks for Visiting \n")
        else: 
            print("Enter a valid option \n")
            updatemarks()
    def updatemobile():
        cnfrmMno=input("Confirm to edit mobile no. (y/n)").lower()
        if cnfrmMno=="y":
            i=1
            while True:
                umn=int(input("Enter ID of the student: "))
                umn1=int(input("Enter new mobile no.: "))
                c.execute("update Student set Mobile='umn1' where ID='umn'")
                print("Mobile no. UPDATED")
                choicemobile=input("Do you want to update another mobile no. (y/n)").lower()
                if choicemobile=="n":
                    break
        elif cnfrmMno=="n":
            print("Thanks for Visiting \n")
        else:
            print("Enter a valid option\n")
            updatemobile()
    def updateemail():
        cnfrmemail=input("Confirm to update a name (y/n): ").lower()
        if cnfrmemail=="y":
            i=1
            while True:
                ue=int(input("Enter the ID of the student to Update: "))
                ue1=input("Enter new email ID: ")
                c.execute("update Student set Email='ue1' where ID='ue'")
                print("Email UPDATED")
                choiceemail=input("Do you want to edit more emails of the students (y/n)").lower()
                if choicemail=="n":
                    break
                    print("Thanks for visiting")
        elif cnfrmemail=="n":
            print("Thanks for visiting \n")
        else:
            print("Enter a valid option")
            updateemail()
    choiceuf=int(input("Enter your choice \n 1. UPDATE ID \n 2. UPDATE NAME \n 3. UPDATE MARKS \n 4.UPDATE MOBILE NUMBER \n 5. UPDATE EMAIL \n"))
    if choiceuf==1:
        a=updateid()
        a
    elif choiceuf==2:
        updatename()
    elif choiceuf==3:
        updatemarks()
    elif choiceuf==4:
        updatemobile()
    elif choiceuf==5:
        updateemail()
    else:
        print("Enter a valid option")
        updatefunction()
    

In [28]:
def choice():
    print("WELCOME TO THE STUDENTS TABLE IN DUCAT DATABASE \n")
    operation=int(input("HOW CAN WE HELP YOU \n 1. INSERT DATA \n 2. READ DATA \n 3. DELTE DATA \n 4. UPDATE DATA \n 5: EXIT THE PAGE \n \n  PLEASE ENTER YOUR CHOICE: "))
    if operation==1:
        insert()
    elif operation==2:
        read()
    elif operation==3:
        delete()
    elif operation==4:
        updatefunction()
    elif operation==5:
        print("\n Thanks for Visiting \n")
    else:
        print("Enter a valid option")
        choice()
choice()

WELCOME TO THE STUDENTS TABLE IN DUCAT DATABASE 



KeyboardInterrupt: Interrupted by user

In [1]:
#class and object
#keyword of "class"= class
"syntax for class= class classname:"

'syntax for class= class classname:'

In [5]:
class ducat:
    def java(object):
        print("I am java function")

In [6]:
d=ducat()
d

In [7]:
d.java()#d.java(Object)

I am java function


In [5]:
#inheritance type
#1. simple
#2. herarchy
#3. multileve

In [8]:
class papa:
    def __init__(self):
        print("Self calling function: ")
class beta(papa):
    def sample(self):
        print("Sample product")

In [9]:
p=papa()

Self calling function: 


In [10]:
p

In [11]:
p=beta()

Self calling function: 


In [12]:
p.sample()

Sample product


In [13]:
p.__init__()

Self calling function: 


In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
a1=np.array([2,3])
for i in a1:
    print(a*i)

[ 2  4  6  8 10]
[ 3  6  9 12 15]


In [4]:
a=np.arange(1,7,2)

In [5]:
a

array([1, 3, 5])

In [5]:
import numpy as np

In [5]:
my_list=[1,2,3,4]
print("List: ",my_list ,"\t type: ",type(my_list))

List:  [1, 2, 3, 4] 	 type:  <class 'list'>


In [6]:
l=my_list
l*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
l*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [9]:
my=np.array(my_list)
my

array([1, 2, 3, 4])

In [10]:
print("data:",my,"\t type:",type(my))

data: [1 2 3 4] 	 type: <class 'numpy.ndarray'>


In [11]:
my.shape

(4,)

In [12]:
np.array(my_list)

array([1, 2, 3, 4])

In [9]:
matrix=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [10]:
len(matrix)

4

In [11]:
type(matrix)

list

In [12]:
len(matrix),type(matrix)

(4, list)

In [13]:
matrix.reshape(2,2)

AttributeError: 'list' object has no attribute 'reshape'

In [14]:
na=np.array(matrix)
na,type(na)

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 numpy.ndarray)

In [15]:
na.shape

(4, 3)

In [3]:
import pandas as pd
import numpy as np

In [2]:
l=[10,20,30,40,50]
l

[10, 20, 30, 40, 50]